server:
  port: 8410
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 119.45.229.83:8848
  datasource:
    url: jdbc:mysql://119.45.229.83/oasys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: wy102102
  jackson:
    default-property-inclusion: non_null
  cache:
    type: redis
    cache-names: permission-role