server:
  port: 8440
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:mysql://119.45.229.83/oasys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: wy102102
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 119.45.229.83:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  file-bucket-name: files
  profile-picture-bucket-name: profile-pictures